"use client";
import { useEffect, useState } from "react";
import { useSearchParams, useRouter } from "next/navigation";
import AppShell from "@/components/AppShell";
import { Card, Button, Input, Label, Select } from "@/components/UI";
import { supabase } from "@/lib/supabase";
const initialForm = { company_id: "", requester_name: "", employee_name: "", description: "", status: "open", priority: "medium" };
export default function NovoAtendimentoPage() {
  const searchParams = useSearchParams(); const router = useRouter(); const companyIdFromQuery = searchParams.get("companyId");
  const [empresas, setEmpresas] = useState([]); const [form, setForm] = useState({ ...initialForm, company_id: companyIdFromQuery || "" }); const [loading, setLoading] = useState(false); const [erro, setErro] = useState(""); const [sucesso, setSucesso] = useState("");
  useEffect(() => { async function carregarEmpresas() { if (!supabase) { setErro("Supabase não configurado."); return; } const { data, error } = await supabase.from("companies").select("id, trade_name, cnpj").order("trade_name", { ascending: true }); if (error) { setErro(error.message); } else { setEmpresas(data || []); } } carregarEmpresas(); }, []);
  function handleChange(field, value) { setForm((prev) => ({ ...prev, [field]: value })); }
  async function handleSubmit(e) { e.preventDefault(); setErro(""); setSucesso(""); if (!supabase) { setErro("Supabase não configurado."); return; } if (!form.company_id) { setErro("Selecione uma empresa."); return; } if (!form.description.trim()) { setErro("Descreva a solicitação."); return; } setLoading(true); const payload = { company_id: form.company_id, requester_name: form.requester_name.trim() || null, employee_name: form.employee_name.trim() || null, description: form.description.trim(), status: form.status, priority: form.priority }; const { data, error } = await supabase.from("tickets").insert(payload).select("id, protocol").single(); if (error) { setErro(error.message); } else { setSucesso(`Atendimento criado com protocolo ${data?.protocol || "-"}.`); setTimeout(() => router.push("/atendimentos"), 1200); } setLoading(false); }
  return (<AppShell title="Novo atendimento" subtitle="Vincule o atendimento a uma empresa já cadastrada e gere o protocolo."><Card><form onSubmit={handleSubmit} className="p-5 grid md:grid-cols-2 gap-4"><div className="md:col-span-2"><Label>Empresa</Label><Select value={form.company_id} onChange={(e) => handleChange("company_id", e.target.value)}><option value="">Selecione a empresa</option>{empresas.map((empresa) => (<option key={empresa.id} value={empresa.id}>{empresa.trade_name} {empresa.cnpj ? `- ${empresa.cnpj}` : ""}</option>))}</Select></div><div><Label>Nome do solicitante</Label><Input value={form.requester_name} onChange={(e) => handleChange("requester_name", e.target.value)} /></div><div><Label>Nome do funcionário</Label><Input value={form.employee_name} onChange={(e) => handleChange("employee_name", e.target.value)} /></div><div><Label>Status inicial</Label><Select value={form.status} onChange={(e) => handleChange("status", e.target.value)}><option value="open">Aberto</option><option value="in_progress">Em andamento</option><option value="waiting">Aguardando</option></Select></div><div><Label>Prioridade</Label><Select value={form.priority} onChange={(e) => handleChange("priority", e.target.value)}><option value="low">Baixa</option><option value="medium">Média</option><option value="high">Alta</option><option value="urgent">Urgente</option></Select></div><div className="md:col-span-2"><Label>Descrição da solicitação</Label><textarea className="w-full rounded-2xl border border-slate-300 bg-white px-4 py-3 text-sm outline-none focus:ring-2 focus:ring-slate-300 min-h-[140px]" value={form.description} onChange={(e) => handleChange("description", e.target.value)} placeholder="Exemplo: segunda via do cartão do colaborador..." /></div>{erro ? <p className="md:col-span-2 text-sm text-red-600">{erro}</p> : null}{sucesso ? <p className="md:col-span-2 text-sm text-emerald-600">{sucesso}</p> : null}<div className="md:col-span-2 flex gap-2"><Button type="submit" disabled={loading}>{loading ? "Salvando..." : "Criar atendimento"}</Button><Button type="button" variant="outline" onClick={() => history.back()}>Voltar</Button></div></form></Card></AppShell>);
}

